export const Types = {
  OFFLINE: 'OFFLINE',
  ONLINE: 'ONLINE',

  FETCH_OUTLETS: 'FETCH_OUTLETS',
  FETCH_OUTLETS_SUCCESS: 'FETCH_OUTLETS_SUCCESS',
  FETCH_OUTLETS_FAILED: 'FETCH_OUTLETS_FAILED',

  FETCH_SHOPPERS: 'FETCH_SHOPPERS',
  FETCH_SHOPPERS_SUCCESS: 'FETCH_SHOPPERS_SUCCESS',
  FETCH_SHOPPERS_FAILED: 'FETCH_SHOPPERS_FAILED',

  FETCH_ADVERTISEMENTS: 'FETCH_ADVERTISEMENTS',
  FETCH_ADVERTISEMENTS_SUCCESS: 'FETCH_ADVERTISEMENTS_SUCCESS',
  FETCH_ADVERTISEMENTS_FAILED: 'FETCH_ADVERTISEMENTS_FAILED',

  FETCH_CATEGORIES_FOR_REVIEW: 'FETCH_CATEGORIES_FOR_REVIEW',
  FETCH_CATEGORIES_FOR_REVIEW_SUCCESS: 'FETCH_CATEGORIES_FOR_REVIEW_SUCCESS',
  FETCH_CATEGORIES_FOR_REVIEW_FAILED: 'FETCH_CATEGORIES_FOR_REVIEW_FAILED',

  FETCH_ADVERTISEMENTS_FOR_REVIEW: 'FETCH_ADVERTISEMENTS_FOR_REVIEW',
  FETCH_ADVERTISEMENTS_FOR_REVIEW_SUCCESS: 'FETCH_ADVERTISEMENTS_FOR_REVIEW_SUCCESS',
  FETCH_ADVERTISEMENTS_FOR_REVIEW_FAILED: 'FETCH_ADVERTISEMENTS_FOR_REVIEW_FAILED',

  UPDATE_ADVERTISEMENT_FOR_REVIEW: 'UPDATE_ADVERTISEMENT_FOR_REVIEW',
  UPDATE_ADVERTISEMENT_FOR_REVIEW_SUCCESS: 'UPDATE_ADVERTISEMENT_FOR_REVIEW_SUCCESS',
  UPDATE_ADVERTISEMENT_FOR_REVIEW_FAILED: 'UPDATE_ADVERTISEMENT_FOR_REVIEW_FAILED',

  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  REGISTER: 'REGISTER',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILED: 'REGISTER_FAILED',

  FORGET_PASSWORD: 'FORGET_PASSWORD',
  FORGET_PASSWORD_SUCCESS: 'FORGET_PASSWORD_SUCCESS',
  FORGET_PASSWORD_FAILED: 'FORGET_PASSWORD_FAILED',
};
