export const Types = {
  OFFLINE: 'OFFLINE',
  ONLINE: 'ONLINE',

  FETCH_OUTLETS: 'FETCH_OUTLETS',
  FETCH_OUTLETS_SUCCESS: 'FETCH_OUTLETS_SUCCESS',
  FETCH_OUTLETS_FAILED: 'FETCH_OUTLETS_FAILED',

  FETCH_SHOPPERS: 'FETCH_SHOPPERS',
  FETCH_SHOPPERS_SUCCESS: 'FETCH_SHOPPERS_SUCCESS',
  FETCH_SHOPPERS_FAILED: 'FETCH_SHOPPERS_FAILED',

  FETCH_ADVERTISEMENTS: 'FETCH_ADVERTISEMENTS',
  FETCH_ADVERTISEMENTS_SUCCESS: 'FETCH_ADVERTISEMENTS_SUCCESS',
  FETCH_ADVERTISEMENTS_FAILED: 'FETCH_ADVERTISEMENTS_FAILED',

  FETCH_CATEGORIES_FOR_REVIEW: 'FETCH_CATEGORIES_FOR_REVIEW',
  FETCH_CATEGORIES_FOR_REVIEW_SUCCESS: 'FETCH_CATEGORIES_FOR_REVIEW_SUCCESS',
  FETCH_CATEGORIES_FOR_REVIEW_FAILED: 'FETCH_CATEGORIES_FOR_REVIEW_FAILED',

  FETCH_ADVERTISEMENTS_FOR_REVIEW: 'FETCH_ADVERTISEMENTS_FOR_REVIEW',
  FETCH_ADVERTISEMENTS_FOR_REVIEW_SUCCESS: 'FETCH_ADVERTISEMENTS_FOR_REVIEW_SUCCESS',
  FETCH_ADVERTISEMENTS_FOR_REVIEW_FAILED: 'FETCH_ADVERTISEMENTS_FOR_REVIEW_FAILED',

  UPDATE_ADVERTISEMENT_FOR_REVIEW: 'UPDATE_ADVERTISEMENT_FOR_REVIEW',
  UPDATE_ADVERTISEMENT_FOR_REVIEW_SUCCESS: 'UPDATE_ADVERTISEMENT_FOR_REVIEW_SUCCESS',
  UPDATE_ADVERTISEMENT_FOR_REVIEW_FAILED: 'UPDATE_ADVERTISEMENT_FOR_REVIEW_FAILED',

  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  REGISTER: 'REGISTER',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILED: 'REGISTER_FAILED',

  FORGET_PASSWORD: 'FORGET_PASSWORD',
  FORGET_PASSWORD_SUCCESS: 'FORGET_PASSWORD_SUCCESS',
  FORGET_PASSWORD_FAILED: 'FORGET_PASSWORD_FAILED',

  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILED: 'CHANGE_PASSWORD_FAILED',

  LOGOUT: 'LOGOUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILED: 'LOGOUT_FAILED',

  FETCH_BRANDS: 'FETCH_BRANDS',
  FETCH_BRANDS_SUCCESS: 'FETCH_BRANDS_SUCCESS',
  FETCH_BRANDS_FAILED: 'FETCH_BRANDS_FAILED',

  FETCH_ADVERTISEMENTS_BY_BRANDS: 'FETCH_ADVERTISEMENTS_BY_BRANDS',
  FETCH_ADVERTISEMENTS_BY_BRANDS_SUCCESS: 'FETCH_ADVERTISEMENTS_BY_BRANDS_SUCCESS',
  FETCH_ADVERTISEMENTS_BY_BRANDS_FAILED: 'FETCH_ADVERTISEMENTS_BY_BRANDS_FAILED',

  CLEAR_ADVERTISEMENTS_BY_BRANDS: 'CLEAR_ADVERTISEMENTS_BY_BRANDS',

  UPLOAD_FILE: 'UPLOAD_FILE',
  UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
  UPLOAD_FILE_FAILED: 'UPLOAD_FILE_FAILED',

  SAVE_RECEIPTS: 'SAVE_RECEIPTS',
  SAVE_RECEIPTS_SUCCESS: 'SAVE_RECEIPTS_SUCCESS',
  SAVE_RECEIPTS_FAILED: 'SAVE_RECEIPTS_FAILED',

  FETCH_RECEIPTS: 'FETCH_RECEIPTS',
  FETCH_RECEIPTS_SUCCESS: 'FETCH_RECEIPTS_SUCCESS',
  FETCH_RECEIPTS_FAILED: 'FETCH_RECEIPTS_FAILED',

  REQUEST_RESET_PASSWORD_OTP: 'REQUEST_RESET_PASSWORD_OTP',
  REQUEST_RESET_PASSWORD_OTP_SUCCESS: 'REQUEST_RESET_PASSWORD_OTP_SUCCESS',
  REQUEST_RESET_PASSWORD_OTP_FAILED: 'REQUEST_RESET_PASSWORD_OTP_FAILED',

  VERIFY_RESET_PASSWORD_OTP: 'VERIFY_RESET_PASSWORD_OTP',
  VERIFY_RESET_PASSWORD_OTP_SUCCESS: 'VERIFY_RESET_PASSWORD_OTP_SUCCESS',
  VERIFY_RESET_PASSWORD_OTP_FAILED: 'VERIFY_RESET_PASSWORD_OTP_FAILED',

  FETCH_USER_PROFILE: 'FETCH_USER_PROFILE',
  FETCH_USER_PROFILE_SUCCESS: 'FETCH_USER_PROFILE_SUCCESS',
  FETCH_USER_PROFILE_FAILED: 'FETCH_USER_PROFILE_FAILED',

  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
  UPDATE_USER_PROFILE_SUCCESS: 'UPDATE_USER_PROFILE_SUCCESS',
  UPDATE_USER_PROFILE_FAILED: 'UPDATE_USER_PROFILE_FAILED',

  FETCH_CATEGORIES_FOR_HOME: 'FETCH_CATEGORIES_FOR_HOME',
  FETCH_CATEGORIES_FOR_HOME_SUCCESS: 'FETCH_CATEGORIES_FOR_HOME_SUCCESS',
  FETCH_CATEGORIES_FOR_HOME_FAILED: 'FETCH_CATEGORIES_FOR_HOME_FAILED',

  FETCH_TRENDING_FEATURES: 'FETCH_TRENDING_FEATURES',
  FETCH_TRENDING_FEATURES_SUCCESS: 'FETCH_TRENDING_FEATURES_SUCCESS',
  FETCH_TRENDING_FEATURES_FAILED: 'FETCH_TRENDING_FEATURES_FAILED',

  FEATURE_INCREMENT_VIEW_COUNT: 'FEATURE_INCREMENT_VIEW_COUNT',
  FEATURE_INCREMENT_VIEW_COUNT_SUCCESS: 'FEATURE_INCREMENT_VIEW_COUNT_SUCCESS',
  FEATURE_INCREMENT_VIEW_COUNT_FAILED: 'FEATURE_INCREMENT_VIEW_COUNT_FAILED',

  REQUEST_LOGIN_OTP: 'REQUEST_LOGIN_OTP',
  REQUEST_LOGIN_OTP_SUCCESS: 'REQUEST_LOGIN_OTP_SUCCESS',
  REQUEST_LOGIN_OTP_FAILED: 'REQUEST_LOGIN_OTP_FAILED',

  LOGIN_WITH_OTP: 'LOGIN_WITH_OTP',
  LOGIN_WITH_OTP_SUCCESS: 'LOGIN_WITH_OTP_SUCCESS',
  LOGIN_WITH_OTP_FAILED: 'LOGIN_WITH_OTP_FAILED',
};
