export const CONSTANTS = {
    SHOW_ALL: 'SHOW ALL',
    PICKER_STRING_SEPARATOR: '(',
    FACTS_RN_PENDING_REVIEW_CATEGORY: 'FACTS_RN_PENDING_REVIEW_CATEGORY',
    LEFT_OPERATION: 'SKIP',
    RIGHT_OPERATION: 'APPROVE',
    NONE: 'NONE',
    FACTS_RN_AUTH_TOKEN: 'FACTS_RN_AUTH_TOKEN',
    FAILURE: 'FAILURE',
    INVALID_LOGIN_CREDENTIALS: 'Invalid login credentials',
};